# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hdws_ZIhHb10g93DMphani7FlZtBXeus
"""

import pandas as pd
base = pd.read_csv("/content/iris.data")

base

previsores = base.iloc[: , :4].values
previsores
classe = base.iloc[:,4].values

classe

from sklearn.preprocessing import LabelEncoder

labelencoder_classe = LabelEncoder()
classe = labelencoder_classe.fit_transform(classe)

classe

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

previsores = scaler.fit_transform(previsores)

previsores

from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, class_test = train_test_split(previsores, classe, test_size=0.25, random_state=0)

from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
acuracia = accuracy_score(class_test, previsoes)
acuracia

matriz = confusion_matrix(class_test, previsoes) 
matriz